In [2]:
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [3]:
data = pd.read_csv('dataset.csv')
data.columns

Index(['Date', 'Latitude', 'Longitude', 'Precipitation', 'Temperature',
       'Relative Humidity', 'Solar Radiation', 'Atmospheric Pressure',
       'Wind Speed', 'Wind Direction', 'PM10', 'PM2.5'],
      dtype='object')

In [6]:

data.describe()

,Latitude,Longitude,Precipitation,Temperature,Relative Humidity,Solar Radiation,Atmospheric Pressure,Wind Speed,Wind Direction,PM10,PM2.5
count,205805.000000,205805.000000,202532.000000,201891.000000,191934.000000,198708.000000,200993.000000,198954.000000,197756.000000,198989.000000,163196.000000
mean,25.713618,-100.294250,0.005351,23.394571,54.878767,-0.442631,715.424273,8.966349,129.436032,60.779100,20.871789
std,0.071372,0.157047,0.249587,23.628900,38.994736,77.702804,9.341355,5.609006,99.856999,42.508853,15.282751
min,25.575383,-100.585833,0.000000,-9999.000000,-9999.000000,-9999.000000,655.400000,0.100000,-9999.000000,2.000000,0.000000
25%,25.665280,-100.412778,0.000000,18.600000,38.000000,0.000000,709.900000,4.900000,68.000000,35.000000,11.000000
50%,25.729787,-100.310028,0.000000,24.290000,56.000000,0.007000,714.500000,8.100000,107.000000,52.000000,17.320000
75%,25.783331,-100.188055,0.000000,28.800000,73.000000,0.275000,721.700000,12.300000,156.000000,74.000000,27.000000
max,25.801940,-99.995334,67.800000,112.390000,714.200000,7.655000,747.600000,188.800000,360.000000,1001.000000,442.000000

In [5]:
data.nunique()

Date                    14255
Latitude                   15
Longitude                  15
Precipitation             149
Temperature              4398
Relative Humidity         107
Solar Radiation          1362
Atmospheric Pressure      664
Wind Speed                602
Wind Direction            361
PM10                     4006
PM2.5                    6358
dtype: int64

In [12]:
data.loc[(data == -9999).any(axis=1)]

,Date,Latitude,Longitude,Precipitation,Temperature,Relative Humidity,Solar Radiation,Atmospheric Pressure,Wind Speed,Wind Direction,PM10,PM2.5
56268,2023-07-17 16:00:00,25.783331,-100.585833,0.0,-9999.00,20.0,0.61,711.9,15.6,80.0,27.0,NaN
83232,2023-05-14 06:00:00,25.600870,-99.995334,0.0,19.11,79.0,-9999.00,701.3,10.8,96.0,31.0,13.44
84576,2023-07-09 06:00:00,25.600870,-99.995334,0.0,23.16,81.0,-9999.00,698.9,5.2,101.0,22.0,4.05
85416,2023-08-13 06:00:00,25.600870,-99.995334,0.0,24.64,63.0,-9999.00,700.3,5.8,117.0,49.0,8.00
93455,2022-11-27 05:00:00,25.665280,-100.412778,0.0,10.38,-9999.0,0.00,714.9,3.2,30.0,130.0,57.00
93456,2022-11-27 06:00:00,25.665280,-100.412778,0.0,10.23,-9999.0,0.00,714.9,2.6,30.0,119.0,34.00
93624,2022-12-04 06:00:00,25.665280,-100.412778,0.0,17.09,2.0,-9999.00,722.3,1.8,12.0,27.0,1.71
96311,2023-03-26 06:00:00,25.665280,-100.412778,0.0,19.42,81.0,-9999.00,711.5,5.1,-9999.0,79.0,26.00
96312,2023-03-26 07:00:00,25.665280,-100.412778,0.0,18.98,83.0,-9999.00,712.0,3.8,-9999.0,77.0,26.00
97823,2023-05-28 06:00:00,25.665280,-100.412778,0.0,21.12,77.0,-9999.00,716.9,10.8,10.0,20.0,8.00
97824,2023-05-28 07:00:00,25.665280,-100.412778,0.0,18.39,83.0,-9999.00,717.4,5.1,18.0,7.0,2.00
97825,2023-05-28 08:00:00,25.665280,-100.412778,0.0,19.28,82.0,-9999.00,717.6,3.1,26.0,4.0,1.00
97826,2023-05-28 09:00:00,25.665280,-100.412778,0.0,22.14,77.0,-9999.00,717.6,3.5,28.0,4.0,2.00
98663,2023-07-02 06:00:00,25.665280,-100.412778,0.0,25.05,74.0,-9999.00,714.6,9.9,19.0,14.0,6.00
98831,2023-07-09 06:00:00,25.665280,-100.412778,0.0,24.43,78.0,-9999.00,714.3,6.5,16.0,18.0,6.00
182344,2023-04-16 06:00:00,25.801940,-100.343056,0.0,22.65,62.0,0.00,716.6,17.6,-9999.0,55.0,14.00

In [3]:
target_vars = ['PM10', 'PM2.5']

,Date,Latitude,Longitude,Precipitation,Temperature,Relative Humidity,Solar Radiation,Atmospheric Pressure,Wind Speed,Wind Direction,PM10,PM2.5
0,2022-01-01 00:00:00,25.791343,-100.078176,0.0,21.65,59.0,0.0,715.7,6.5,285.0,142.0,111.00
1,2022-01-01 01:00:00,25.791343,-100.078176,0.0,21.21,59.0,0.0,715.5,7.1,284.0,168.0,112.16
2,2022-01-01 02:00:00,25.791343,-100.078176,0.0,21.21,62.0,0.0,715.4,7.7,290.0,203.0,139.31
3,2022-01-01 03:00:00,25.791343,-100.078176,0.0,20.44,59.0,0.0,715.1,8.2,294.0,262.0,177.68
4,2022-01-01 04:00:00,25.791343,-100.078176,0.0,19.80,59.0,0.0,715.1,8.1,287.0,185.0,134.21